Propagate error when observing status failure android
PhilipsHue/flutter_reactive_ble pull request #129
Opened 2020-10-22 10:04 UTC by remonh87

2020-10-22 13:06 UTC, werediver requested changes

2020-10-22 13:06 UTC, werediver commented on CHANGELOG.md
> +* Prevent lib from crashing when listen to blestatus status throws an error on Android.
- "lib"? ("library")
- "bblestatus"?? (either use `in-line code` quatoation and refer to an existing type or whatever, or [preferably?] use natural language)

2020-10-22 13:06 UTC, werediver commented on android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/BleStatusHandler.kt
> +import com.signify.hue.flutterreactiveble.ProtobufModel as pb
Why reordering?

2020-10-23 11:01 UTC, remonh87 commented on android/src/main/kotlin/com/signify/hue/flutterreactiveble/channelhandlers/BleStatusHandler.kt
> +import com.signify.hue.flutterreactiveble.ProtobufModel as pb
android studio did it :)

2020-10-23 11:08 UTC, werediver approved these changes

2020-10-23 11:16 UTC, merged