Deinitialize in onDetachedFromEngine on Android
PhilipsHue/flutter_reactive_ble pull request #519
Opened 2022-02-17 19:36 UTC by Rexios80

Without this, devices stay connected to detached native code and behave unexpectedly when reattached to flutter

2022-02-17 20:03 UTC, Taym95 requested changes

2022-02-17 20:03 UTC, Taym95 commented on packages/reactive_ble_mobile/android/src/main/kotlin/com/signify/hue/flutterreactiveble/PluginController.kt
> +    internal fun deinitialize() {
can be private

2022-02-17 21:23 UTC, Rexios80 commented
This crashes if there aren't any devices connected

2022-02-17 21:58 UTC, Rexios80 commented
Fixed that. Lateinit variables are dangerous.

Also I used the current instance of the plugin as the method handler. For this plugin it doesn't look like that changes anything, but it matches the new flutter plugin template and can prevent issues in the future.

2022-02-18 05:40 UTC, remonh87 approved these changes
yes much better thanks!!

2022-02-18 10:40 UTC, Taym95 approved these changes

2022-02-21 19:40 UTC, merged

2022-03-04 02:06 UTC, Rexios80 commented
Any idea when this will be released?

2022-03-04 08:48 UTC, Taym95 commented
@Rexios80 we will release a new version ASAP