Federated implementations
PhilipsHue/flutter_reactive_ble pull request #599
Opened 2022-08-11 13:08 UTC by trik

Following the discussion in #544, i'm trying to publish a web implementation of this plugin but i'm facing a couple of issues:

- ReactiveBlePlatform class exposes the set instance method to enable other platform-specific implementations but the instance is currently always re-set using ReactiveBleMobilePlatformFactory https://github.com/PhilipsHue/flutter_reactive_ble/blob/master/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L107

- platformIsAndroid variable is currently set using Platform.isAndroid, which rises an exeception in non-native environments

2022-08-25 09:01 UTC, Taym95 requested changes

2022-08-25 09:01 UTC, Taym95 commented on packages/flutter_reactive_ble/lib/src/reactive_ble.dart
> +        ReactiveBlePlatform.instance =
` ReactiveBlePlatform.instance ??= const ReactiveBleMobilePlatformFactory().create();`

2022-08-25 09:19 UTC, Taym95 commented on packages/flutter_reactive_ble/lib/src/reactive_ble.dart
> +        platformIsAndroid: () => !kIsWeb && Platform.isAndroid,
:+1:

2022-08-28 00:46 UTC, Taym95 approved these changes

2022-09-12 06:54 UTC, trik commented
@Taym95 i think this code needs to be refactored. it's working good with a custom implementation but it's throwing a LateInitializationError when using the default one (reactive_ble_mobile).

```dart
try {
  ReactiveBlePlatform.instance;
} on LateInitializationError {
  ReactiveBlePlatform.instance = const ReactiveBleMobilePlatformFactory().create();
}
```

2024-01-11 14:01 UTC, closed without merging