Bumps to Dart 2.17 minimum and upgrades melos to 3.1.0
PhilipsHue/flutter_reactive_ble pull request #762
Opened 2023-07-05 17:36 UTC by ened

2023-07-05 17:44 UTC, ened commented
@Taym95 @remonh87 - does this change need a changelog in order to be merged? It is the foundation for other upcoming improvements. Thank you.

2023-07-05 19:30 UTC, remonh87 approved these changes
Looks good to me. maybe someone of hue can have a  look at it as well?

2023-07-06 10:49 UTC, Taym95 requested changes

2023-07-06 10:49 UTC, Taym95 commented on pubspec.yaml
> +name: reactive_ble_workspace
```suggestion
name: flutter_reactive_ble workspace
```

2023-07-06 11:31 UTC, Taym95 approved these changes

2023-07-06 11:35 UTC, ened commented
@Taym95 could you to merge ? I do not have the permission. Thank you

2023-07-06 13:34 UTC, merged